apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fedora
  name: fedora
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fedora
  template:
    metadata:
      labels:
        app: fedora
    spec:
      containers:
        - image: rdegtyarev/fedora-pip:0.1.0
          imagePullPolicy: Always
          name: fedora
          command: ["/bin/sleep", "365d"]
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
