---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-approle-demo
  labels:
    role: vault-approle-demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      role: vault-approle-demo
  template:
    metadata:
      labels:
        role: vault-approle-demo
    spec:
      shareProcessNamespace: true
      # initContainers:
      #   - name: init-app-config
      #     image: vault:1.9.0
      #     imagePullPolicy: IfNotPresent
      #     securityContext:
      #       runAsUser: 10001
      #       runAsNonRoot: true
      #       capabilities:
      #         add:
      #           - IPC_LOCK
      #     args:
      #       - "agent"
      #       - "-config=/etc/vault/config/vault-agent.hcl"
      #     env:
      #       - name: SKIP_SETCAP
      #         value: 'true'
      #     volumeMounts:
      #       - mountPath: /etc/vault/config
      #         name: vault-config
      #       - mountPath: /etc/vault/config/approle
      #         name: approle-config
      containers:
        # - name: shell
        #   image: busybox
        #   resources:
        #     limits:
        #       cpu: 200m
        #       memory: 256Mi
        #     requests:
        #       cpu: 100m
        #       memory: 128Mi
        #   securityContext:
        #     capabilities:
        #       add:
        #         - SYS_PTRACE
        #   stdin: true
        #   tty: true
        #   volumeMounts:
        #     - mountPath: /app/config
        #       name: approle-config
        - image: rdegtyarev/fedora-pip:0.2.0
          imagePullPolicy: Always
          name: fedora
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: APPROLE_ROLE_ID
              valueFrom:
                configMapKeyRef:
                  name: vault-agent-config
                  key: app-role-id
            - name: APPROLE_WRAPPEN_TOKEN_FILE
              value: /app/config/wrapped_token
            - name: APPROLE_UNWRAPPEN_TOKEN_FILE
              value: /app/config/unwrapped_token
            - name: APPROLE_VAULT_ADDR
              value: http://vault.clokub-14-02:8200
            - name: APPROLE_SECRET_MOUNT_POINT
              value: secrets
            - name: APPROLE_SECRET_PATH
              value: /k11s/demo/app/nginx
          command: ["/bin/sleep", "365d"]
          volumeMounts:
            - mountPath: /app/config
              name: approle-config
        - name: render-app-config
          image: vault:1.9.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
            capabilities:
              add:
                - IPC_LOCK
          args:
            - "agent"
            - "-config=/etc/vault/config/vault-agent-reload.hcl"
          env:
            - name: SKIP_SETCAP
              value: 'true'
          volumeMounts:
            - mountPath: /etc/vault/config
              name: vault-config
            - mountPath: /etc/vault/config/approle
              name: approle-config
      volumes:
        - name: vault-config
          configMap:
            name: vault-agent-config
        - name: approle-config
          emptyDir:
            medium: Memory
